antobot_lio_fast:
  ros__parameters:
    imu_topic: /livox/imu_192_168_1_200
    lidar_topic: /livox/lidar_192_168_1_200
    body_frame: laser_link_front
    world_frame: odom
    print_time_cost: true
    turn_over_mid360: false
    out_put_base_odom: true

    lidar2base_x: -0.685
    lidar2base_y: 0.0
    lidar2base_z: 0.0

    out_put_base_odom_to_tum: true
    out_put_wheel_odom_to_tum: false

    lidar_filter_num: 6
    lidar_min_range: 0.5
    lidar_max_range: 30.0
    scan_resolution: 0.2
    map_resolution: 0.5

    cube_len: 150
    det_range: 60
    move_thresh: 1.5

    na: 0.01
    ng: 0.01
    nba: 0.0001
    nbg: 0.0001

    imu_init_num: 20
    near_search_num: 4
    ieskf_max_iter: 5

    gravity_align: true
    esti_il: true

    r_il: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    t_il: [-0.011, -0.02329, 0.04412]
    lidar_cov_inv: 1000.0
